services:
  - type: web
    name: elderly-care-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true